language: node_js
node_js:
  - "8"

install:
  - npm install

script:
  - NODE_ENV=production webpack

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local_dir: dist